import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PortalTerreno.com - Lucas Andrews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my economic indicators portal
        </h1>

        <h3 className={styles.description}>
          <u>
            <Link href="/indicadores">Click here</Link>
          </u>{" "}
          to enter the app...
        </h3>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://portfolio-lucas-andrews.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Coded by Lucas Andrews
        </a>
      </footer>
    </div>
  );
}
